### ISSUE TITLE
Concurrent iteration and write on globalLayers

### ISSUE THREAD

**Issue by elffjs** [CrunchyData/pg_tileserv#145]
We've been getting the following panic in testing, using the latest image `cef9df8e8bc3` [from Docker Hub](https://hub.docker.com/r/pramsey/pg_tileserv/tags). Apologies for the long trace but I didn't want to leave anything out, though I suspect only the first block is interesting:

```
fatal error: concurrent map iteration and map write

goroutine 2668 [running]:
runtime.throw(0xca5dc1, 0x26)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:1117 +0x72 fp=0xc000399000 sp=0xc000398fd0 pc=0x438b92
runtime.mapiternext(0xc0003991f0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/map.go:858 +0x54c fp=0xc000399080 sp=0xc000399000 pc=0x41266c
runtime.mapiterinit(0xbb5fa0, 0xc0006679b0, 0xc0003991f0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/map.go:848 +0x1c5 fp=0xc0003990a0 sp=0xc000399080 pc=0x412025
main.getJSONLayers(0xc000460200, 0x0)
	/home/runner/work/pg_tileserv/pg_tileserv/layer.go:100 +0xb6 fp=0xc000399260 sp=0xc0003990a0 pc=0xb1f716
main.requestListHTML(0xd73da8, 0xc00047c000, 0xc000460200, 0x5, 0xc00032d4d8)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:261 +0x1ef fp=0xc000399430 sp=0xc000399260 pc=0xb2918f
main.tileAppHandler.ServeHTTP(0xcc2550, 0xd73da8, 0xc00047c000, 0xc000460200)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:416 +0x298 fp=0xc0003996b8 sp=0xc000399430 pc=0xb2adf8
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004a6180, 0xd73da8, 0xc00047c000, 0xc000460000)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 fp=0xc0003997f0 sp=0xc0003996b8 pc=0x9d90f3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0002e2c60, 0xd73da8, 0xc00047c000, 0xc000460000)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:54 +0x103e fp=0xc000399940 sp=0xc0003997f0 pc=0x9d701e
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xd73da8, 0xc00047c000, 0xc000460000)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:100 +0x8eb fp=0xc000399a88 sp=0xc000399940 pc=0x9d7feb
net/http.HandlerFunc.ServeHTTP(0xc0002b6d40, 0xd73da8, 0xc00047c000, 0xc000460000)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2050 +0x44 fp=0xc000399ab0 sp=0xc000399a88 pc=0x84b5a4
main.setCacheControl.func1(0xd73da8, 0xc00047c000, 0xc000460000)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:447 +0x8c fp=0xc000399b48 sp=0xc000399ab0 pc=0xb2e2cc
net/http.HandlerFunc.ServeHTTP(0xc000282be8, 0xd73da8, 0xc00047c000, 0xc000460000)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2050 +0x44 fp=0xc000399b70 sp=0xc000399b48 pc=0x84b5a4
net/http.serverHandler.ServeHTTP(0xc0002e8460, 0xd73da8, 0xc00047c000, 0xc000460000)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2868 +0xa3 fp=0xc000399ba0 sp=0xc000399b70 pc=0x84eb63
net/http.(*conn).serve(0xc0001c8280, 0xd76878, 0xc0002d2040)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:1933 +0x8cd fp=0xc000399fc8 sp=0xc000399ba0 pc=0x84a08d
runtime.goexit()
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000399fd0 sp=0xc000399fc8 pc=0x46ec61
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2994 +0x39b

goroutine 1 [chan receive, 73 minutes]:
main.handleRequests()
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:550 +0x60d
main.main()
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:198 +0xeb8

goroutine 25 [select]:
github.com/jackc/pgx/v4/pgxpool.(*Pool).backgroundHealthCheck(0xc00022a730)
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.9.2/pgxpool/pool.go:322 +0xbb
created by github.com/jackc/pgx/v4/pgxpool.ConnectConfig
	/home/runner/go/pkg/mod/github.com/jackc/pgx/v4@v4.9.2/pgxpool/pool.go:205 +0x25f

goroutine 34 [IO wait]:
internal/poll.runtime_pollWait(0x7f9a4c0aee98, 0x72, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc000412118, 0x72, 0x0, 0x0, 0xc8e76a)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000412100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000412100, 0xb2676f6a48996c90, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000418048, 0x62ac13e1, 0xc000436dd0, 0x4c8606)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000418048, 0xc000436e20, 0x18, 0xc00008b680, 0x84f05b)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0002e8460, 0xd73bc8, 0xc000418048, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2962 +0x285
net/http.(*Server).ListenAndServe(0xc0002e8460, 0x644ddf, 0x46ec61)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2891 +0xba
main.handleRequests.func1(0xc0002e8460)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:509 +0x2f
created by main.handleRequests
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:506 +0x385

goroutine 36 [syscall, 73 minutes]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	/opt/hostedtoolcache/go/1.16.15/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.16.15/x64/src/os/signal/signal.go:151 +0x45

goroutine 2669 [IO wait]:
internal/poll.runtime_pollWait(0x7f9a4c0aeaf8, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc000484098, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000484080, 0xc00046e101, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000484080, 0xc00046e101, 0x1, 0x1, 0xc0003e0001, 0xc0003e2fa8, 0x86829d)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010010, 0xc00046e101, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc00046e0f0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:672 +0x58
created by net/http.(*connReader).startBackgroundRead
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:668 +0xd5

goroutine 2667 [runnable]:
github.com/spf13/viper.(*Viper).find(0xc0000eaa20, 0xc0003c9860, 0xa, 0x1, 0x18, 0xc0003c9500)
	/home/runner/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1023 +0x1515
	/home/runner/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:728 +0x85
github.com/spf13/viper.(*Viper).GetString(0xc0000eaa20, 0xc911cf, 0xa, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:793 +0x3f
github.com/spf13/viper.GetString(...)
	/home/runner/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:791
main.requestListHTML(0xd73da8, 0xc0000f40e0, 0xc00056eb00, 0x5, 0xc0003d34d8)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:263 +0x21e
main.tileAppHandler.ServeHTTP(0xcc2550, 0xd73da8, 0xc0000f40e0, 0xc00056eb00)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:416 +0x298
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004a6180, 0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0002e2c60, 0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:54 +0x103e
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:100 +0x8eb
net/http.HandlerFunc.ServeHTTP(0xc0002b6d40, 0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2050 +0x44
main.setCacheControl.func1(0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/home/runner/work/pg_tileserv/pg_tileserv/main.go:447 +0x8c
net/http.HandlerFunc.ServeHTTP(0xc000282be8, 0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2050 +0x44
net/http.serverHandler.ServeHTTP(0xc0002e8460, 0xd73da8, 0xc0000f40e0, 0xc00056e900)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0001c80a0, 0xd76878, 0xc00046b880)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:2994 +0x39b

goroutine 2625 [IO wait]:
internal/poll.runtime_pollWait(0x7f9a4c0aedb0, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc000484018, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000484000, 0xc0006675d1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000484000, 0xc0006675d1, 0x1, 0x1, 0xc000500001, 0xc000507fa8, 0x86829d)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010008, 0xc0006675d1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc0006675c0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:672 +0x58
created by net/http.(*connReader).startBackgroundRead
	/opt/hostedtoolcache/go/1.16.15/x64/src/net/http/server.go:668 +0xd5
```

The implicated code seems to be:

https://github.com/CrunchyData/pg_tileserv/blob/262d7cb7d53eb20123849a4fa560b20c5d8703f4/layer.go#L97-L101

In #89 a mutex was placed around the assignment to `globalLayers` in the `loadLayers` function just above this. We will try acquiring the mutex in `getJSONLayers` as well and report back.

**Comment by pramsey** [comment]
Did adding the mutex work?

**Comment by elffjs** [comment]
> Did adding the mutex work?

Hi! Sorry to take so long to get back to you. I finally got around to deploying an image with the lock added and it's been running for a few days without issue. I'll make a small PR in a moment.

**Comment by elffjs** [comment]
Opened! I regret that I can't say why exactly it's happening to us in particular, or offer a nice test.
