### ISSUE TITLE
Error : fatal error: concurrent map writes

### ISSUE THREAD

**Issue by HaudelardUpFactor** [CrunchyData/pg_tileserv#89]
Hello,

I've got this error with the tile-server and it happends each time I've tried to relaunch it.

```
INFO[0000] pg_tileserv latest
INFO[0000] Run with --help parameter for commandline options
INFO[0000] Using config file: /home/tistou/config/pg_tileserv.toml
INFO[0000] Serving HTTP  at http://0.0.0.0:7800/
INFO[0000] Serving HTTPS at http://0.0.0.0:7801/
INFO[0000] Using CoordinateSystem.SRID 3857 with bounds [-2.00375083427892e+07, -2.00375083427892e+07, 2.00375083427892e+07, 2.00375083427892e+07]
INFO[0000] Connected as 'postgres' to 'upfactor-raw' @ '10.0.0.66'
INFO[0004] Serving HTTP  at 0.0.0.0:7800
INFO[0401] GET /os._buildings_footprints_osm/16/33195/22543.pbf  method=GET url=/os._buildings_footprints_osm/16/33195/22543.pbf
INFO[0401] GET /os._buildings_footprints_osm/16/33195/22544.pbf  method=GET url=/os._buildings_footprints_osm/16/33195/22544.pbf
INFO[0401] GET /admin._limites_parcelle_cadastre/16/33195/22544.pbf  method=GET url=/admin._limites_parcelle_cadastre/16/33195/22544.pbf
INFO[0401] GET /admin._limites_parcelle_cadastre/16/33195/22543.pbf  method=GET url=/admin._limites_parcelle_cadastre/16/33195/22543.pbf
fatal error: concurrent map writes

goroutine 35 [running]:
runtime.throw(0xa76e72, 0x15)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:1117 +0x72 fp=0xc000658830 sp=0xc000658800 pc=0x438032
runtime.mapassign_faststr(0x9dbca0, 0xc0001d6030, 0xa71bbe, 0xc, 0x0)
        /home/travis/.gimme/versions/go/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc000658898 sp=0xc000658830 pc=0x416098
main.getSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:110 +0x159 fp=0xc000658900 sp=0xc000658898 pc=0x9778b9
main.renderSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa4f4a0, 0xc000798140, 0xb, 0x2, 0xc0007c69f8, 0x4dd72d)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:116 +0x73 fp=0xc000658980 sp=0xc000658900 pc=0x977a53
main.(*LayerTable).requestSql(0xc0007c6d90, 0xc0007c6e10, 0xc0007c6cc8, 0xc000240380, 0x8, 0x8, 0x1000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:436 +0x8f4 fp=0xc000658c88 sp=0xc000658980 pc=0x9701f4
main.LayerTable.GetTileRequest(0xc00002b600, 0x20, 0xc0002bf580, 0x5, 0xc00002b620, 0x1a, 0x0, 0x0, 0xc0002c0780, 0xc0002bf590, ...)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:93 +0xc5 fp=0xc000658d90 sp=0xc000658c88 pc=0x96d2e5
main.(*LayerTable).GetTileRequest(0xc00055e480, 0x10, 0x81ab, 0x5810, 0xc00002c085, 0x3, 0xf11, 0x410fdfa71be5ef80, 0x4157d8cf7af62ac0, 0x410ff2c3142b6b80, ...)
        <autogenerated>:1 +0x10b fp=0xc000659008 sp=0xc000658d90 pc=0x978d0b
main.requestTile(0xb28428, 0xc0007c8050, 0xc00017c500, 0x0, 0x0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:323 +0x702 fp=0xc000659430 sp=0xc000659008 pc=0x9749c2
main.tileAppHandler.ServeHTTP(0xa9b890, 0xb28428, 0xc0007c8050, 0xc00017c500)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:373 +0x298 fp=0xc0006596b8 sp=0xc000659430 pc=0x975198
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00015a0c0, 0xb28428, 0xc0007c8050, 0xc00017c300)
        /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 fp=0xc0006597f0 sp=0xc0006596b8 pc=0x921df3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000526fc0, 0xb28428, 0xc0007c8050, 0xc00017c300)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8 fp=0xc000659940 sp=0xc0006597f0 pc=0x91ef88
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb27cd8, 0xc0007b8000, 0xc00017c300)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x692 fp=0xc000659a88 sp=0xc000659940 pc=0x920a92
net/http.HandlerFunc.ServeHTTP(0xc000032a00, 0xb27cd8, 0xc0007b8000, 0xc00017c300)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44 fp=0xc000659ab0 sp=0xc000659a88 pc=0x842cc4
main.setCacheControl.func1(0xb27cd8, 0xc0007b8000, 0xc00017c300)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:404 +0x8c fp=0xc000659b48 sp=0xc000659ab0 pc=0x97818c
net/http.HandlerFunc.ServeHTTP(0xc00000e0d8, 0xb27cd8, 0xc0007b8000, 0xc00017c300)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44 fp=0xc000659b70 sp=0xc000659b48 pc=0x842cc4
net/http.serverHandler.ServeHTTP(0xc00061a000, 0xb27cd8, 0xc0007b8000, 0xc00017c300)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2887 +0xa3 fp=0xc000659ba0 sp=0xc000659b70 pc=0x846283
net/http.(*conn).serve(0xc0007980a0, 0xb2a1c0, 0xc00039c000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:1952 +0x8cd fp=0xc000659fc8 sp=0xc000659ba0 pc=0x8417ad
runtime.goexit()
        /home/travis/.gimme/versions/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000659fd0 sp=0xc000659fc8 pc=0x46df01
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:3013 +0x39b

goroutine 1 [chan receive, 6 minutes]:
main.handleRequests()
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:503 +0x60d
main.main()
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:187 +0xeb8

goroutine 5 [select, 3 minutes]:
github.com/jackc/pgx/v4/pgxpool.(*Pool).backgroundHealthCheck(0xc0002360f0)
        /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.9.2/pgxpool/pool.go:322 +0xbb
created by github.com/jackc/pgx/v4/pgxpool.ConnectConfig
        /home/travis/gopath/pkg/mod/github.com/jackc/pgx/v4@v4.9.2/pgxpool/pool.go:205 +0x25f

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f053c4b8da0, 0x72, 0x0)
        /home/travis/.gimme/versions/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0006ec018, 0x72, 0x0, 0x0, 0xa6dc47)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0006ec000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0006ec000, 0x91cdc997b89dccad, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00012a048, 0x608034db, 0xc000050dd0, 0x4c7666)
        /home/travis/.gimme/versions/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00012a048, 0xc000050e20, 0x18, 0xc000082f00, 0x84677b)
        /home/travis/.gimme/versions/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00061a000, 0xb27af8, 0xc00012a048, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2981 +0x285
net/http.(*Server).ListenAndServe(0xc00061a000, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2910 +0xba
main.handleRequests.func1(0xc00061a000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:462 +0x2f
created by main.handleRequests
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:459 +0x385

goroutine 10 [syscall, 6 minutes]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /home/travis/.gimme/versions/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /home/travis/.gimme/versions/go/src/os/signal/signal.go:151 +0x45

goroutine 21 [runnable]:  
fmt.(*fmt).pad(0xc00025e040, 0xc00025e0a8, 0x4, 0x4)
        /home/travis/.gimme/versions/go/src/fmt/format.go:90 +0x34a
fmt.(*fmt).fmtInteger(0xc00025e040, 0xf11, 0xa, 0x76001ca101, 0xa74181, 0x11)
        /home/travis/.gimme/versions/go/src/fmt/format.go:319 +0x1fa
fmt.(*pp).fmtInteger(0xc00025e000, 0xf11, 0x76006ea301)
        /home/travis/.gimme/versions/go/src/fmt/print.go:376 +0x265
fmt.(*pp).printArg(0xc00025e000, 0x9bbae0, 0xc0001ca200, 0x76)
        /home/travis/.gimme/versions/go/src/fmt/print.go:672 +0x94b
fmt.(*pp).doPrint(0xc00025e000, 0xc00074a6d8, 0x1, 0x1)
        /home/travis/.gimme/versions/go/src/fmt/print.go:1157 +0x105
fmt.Fprint(0xb1df00, 0xc0005fe600, 0xc00074a6d8, 0x1, 0x1, 0x9bba01, 0xc0001ca200, 0x0)
        /home/travis/.gimme/versions/go/src/fmt/print.go:232 +0x58
text/template.(*state).printValue(0xc00074a898, 0xb2bd60, 0xc00040c900, 0x9bbae0, 0xc0001ca200, 0x82)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:965 +0xe5
text/template.(*state).walk(0xc00074a898, 0xa4f4a0, 0xc0001ca1e0, 0x99, 0xb2bd60, 0xc00040c900)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:257 +0x3e5
text/template.(*state).walk(0xc00074a898, 0xa4f4a0, 0xc0001ca1e0, 0x99, 0xb2c030, 0xc0005fe7e0)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:264 +0x13c
text/template.(*Template).execute(0xc00016aa80, 0xb1df00, 0xc0005fe600, 0xa4f4a0, 0xc0001ca1e0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:220 +0x1c6
text/template.(*Template).Execute(...)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:203
main.renderSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa4f4a0, 0xc0001ca1e0, 0xb, 0x2, 0xc0007249f8, 0x4dd72d)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:117 +0xb2
main.(*LayerTable).requestSql(0xc000724d90, 0xc000724e10, 0xc000724cc8, 0xc00073c000, 0x1d, 0x1d, 0x1000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:436 +0x8f4
main.LayerTable.GetTileRequest(0xc00008ef80, 0x1c, 0xc000382378, 0x2, 0xc00008efa0, 0x19, 0x0, 0x0, 0xc000093ad0, 0xc000382388, ...)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:93 +0xc5
main.requestTile(0xb28428, 0xc0002377c0, 0xc000710200, 0x0, 0x0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:323 +0x702
main.tileAppHandler.ServeHTTP(0xa9b890, 0xb28428, 0xc0002377c0, 0xc000710200)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:373 +0x298
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00015a0c0, 0xb28428, 0xc0002377c0, 0xc000710000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000526fc0, 0xb28428, 0xc0002377c0, 0xc000710000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb27cd8, 0xc000718000, 0xc000710000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x692
net/http.HandlerFunc.ServeHTTP(0xc000032a00, 0xb27cd8, 0xc000718000, 0xc000710000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
main.setCacheControl.func1(0xb27cd8, 0xc000718000, 0xc000710000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:404 +0x8c
net/http.HandlerFunc.ServeHTTP(0xc00000e0d8, 0xb27cd8, 0xc000718000, 0xc000710000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc00061a000, 0xb27cd8, 0xc000718000, 0xc000710000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001ca000, 0xb2a1c0, 0xc00016a000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:3013 +0x39b

goroutine 11 [runnable]:  
text/template/parse.NodeType.Type(0x0, 0x0)
        /home/travis/.gimme/versions/go/src/text/template/parse/node.go:49
text/template/parse.(*Tree).parse(0xc00015cb40)
        /home/travis/.gimme/versions/go/src/text/template/parse/parse.go:310 +0x27a
text/template/parse.(*Tree).Parse(0xc00015cb40, 0xa8f773, 0x233, 0x0, 0x0, 0x0, 0x0, 0xc0001fe5d0, 0xc000020430, 0x2, ...)
        /home/travis/.gimme/versions/go/src/text/template/parse/parse.go:246 +0x23b
text/template/parse.Parse(0xa71bbe, 0xc, 0xa8f773, 0x233, 0x0, 0x0, 0x0, 0x0, 0xc000020430, 0x2, ...)
        /home/travis/.gimme/versions/go/src/text/template/parse/parse.go:65 +0x11d
text/template.(*Template).Parse(0xc00006a140, 0xa8f773, 0x233, 0xc, 0xe7a560, 0xc000152800)
        /home/travis/.gimme/versions/go/src/text/template/template.go:201 +0x825
main.getSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:106 +0xc6
main.renderSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa4f4a0, 0xc000146500, 0xb, 0x2, 0xc0001529f8, 0x4dd72d)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:116 +0x73
main.(*LayerTable).requestSql(0xc000152d90, 0xc000152e10, 0xc000152cc8, 0xc00000c1e0, 0x1d, 0x1d, 0x1000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:436 +0x8f4
main.LayerTable.GetTileRequest(0xc00008ef80, 0x1c, 0xc000382378, 0x2, 0xc00008efa0, 0x19, 0x0, 0x0, 0xc000093ad0, 0xc000382388, ...)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:93 +0xc5
main.requestTile(0xb28428, 0xc00010e230, 0xc000628200, 0x0, 0x0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:323 +0x702
main.tileAppHandler.ServeHTTP(0xa9b890, 0xb28428, 0xc00010e230, 0xc000628200)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:373 +0x298
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00015a0c0, 0xb28428, 0xc00010e230, 0xc000628000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000526fc0, 0xb28428, 0xc00010e230, 0xc000628000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb27cd8, 0xc00061a0e0, 0xc000628000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x692
net/http.HandlerFunc.ServeHTTP(0xc000032a00, 0xb27cd8, 0xc00061a0e0, 0xc000628000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
main.setCacheControl.func1(0xb27cd8, 0xc00061a0e0, 0xc000628000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:404 +0x8c
net/http.HandlerFunc.ServeHTTP(0xc00000e0d8, 0xb27cd8, 0xc00061a0e0, 0xc000628000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc00061a000, 0xb27cd8, 0xc00061a0e0, 0xc000628000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000146320, 0xb2a1c0, 0xc00006a000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:3013 +0x39b

goroutine 34 [runnable]:  
reflect.implements(0x9e5420, 0x9bc560, 0x40f5bb)
        /home/travis/.gimme/versions/go/src/reflect/type.go:1464 +0x8ab
reflect.(*rtype).Implements(0x9bc560, 0xb30e40, 0x9e5420, 0xb30e40)
        /home/travis/.gimme/versions/go/src/reflect/type.go:1440 +0x73
text/template.printableValue(0x9bc560, 0xc00042a048, 0x98, 0x0, 0x0, 0x9bc560)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:981 +0x99
text/template.(*state).printValue(0xc000746898, 0xb2bd60, 0xc0005fe9f0, 0x9bc560, 0xc00042a048, 0x98)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:961 +0x87
text/template.(*state).walk(0xc000746898, 0xa4f4a0, 0xc00042a000, 0x99, 0xb2bd60, 0xc0005fe9f0)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:257 +0x3e5
text/template.(*state).walk(0xc000746898, 0xa4f4a0, 0xc00042a000, 0x99, 0xb2c030, 0xc00040c480)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:264 +0x13c
text/template.(*Template).execute(0xc000700180, 0xb1df00, 0xc00040c240, 0xa4f4a0, 0xc00042a000, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:220 +0x1c6
text/template.(*Template).Execute(...)
        /home/travis/.gimme/versions/go/src/text/template/exec.go:203
main.renderSqlTemplate(0xa71bbe, 0xc, 0xa8f773, 0x233, 0xa4f4a0, 0xc00042a000, 0xb, 0x2, 0xc0007c29f8, 0x4dd72d)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/util.go:117 +0xb2
main.(*LayerTable).requestSql(0xc0007c2d90, 0xc0007c2e10, 0xc0007c2cc8, 0xc000563980, 0x8, 0x8, 0x1000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:436 +0x8f4
main.LayerTable.GetTileRequest(0xc00002b600, 0x20, 0xc0002bf580, 0x5, 0xc00002b620, 0x1a, 0x0, 0x0, 0xc0002c0780, 0xc0002bf590, ...)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/layer_table.go:93 +0xc5
main.requestTile(0xb28428, 0xc0001a8050, 0xc00009a200, 0x0, 0x0)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:323 +0x702
main.tileAppHandler.ServeHTTP(0xa9b890, 0xb28428, 0xc0001a8050, 0xc00009a200)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:373 +0x298
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00015a0c0, 0xb28428, 0xc0001a8050, 0xc00009a000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000526fc0, 0xb28428, 0xc0001a8050, 0xc00009a000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:138 +0x2a8
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xb27cd8, 0xc0000d4000, 0xc00009a000)
        /home/travis/gopath/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x692
net/http.HandlerFunc.ServeHTTP(0xc000032a00, 0xb27cd8, 0xc0000d4000, 0xc00009a000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
main.setCacheControl.func1(0xb27cd8, 0xc0000d4000, 0xc00009a000)
        /home/travis/gopath/src/github.com/CrunchyData/pg_tileserv/main.go:404 +0x8c
net/http.HandlerFunc.ServeHTTP(0xc00000e0d8, 0xb27cd8, 0xc0000d4000, 0xc00009a000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc00061a000, 0xb27cd8, 0xc0000d4000, 0xc00009a000)
        /home/travis/.gimme/versions/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000798000, 0xb2a1c0, 0xc000700040)
        /home/travis/.gimme/versions/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /home/travis/.gimme/versions/go/src/net/http/server.go:3013 +0x39b

goroutine 12 [IO wait]:   
internal/poll.runtime_pollWait(0x7f053c4b8bd0, 0x72, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0006ec098, 0x72, 0x0, 0x1, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0006ec080, 0xc0001fe1c1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0006ec080, 0xc0001fe1c1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010010, 0xc0001fe1c1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc0001fe1b0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
        /home/travis/.gimme/versions/go/src/net/http/server.go:688 +0xd5

goroutine 22 [IO wait]:   
internal/poll.runtime_pollWait(0x7f053c4b8cb8, 0x72, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005e2018, 0x72, 0x0, 0x1, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005e2000, 0xc0005fe101, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0005e2000, 0xc0005fe101, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000138050, 0xc0005fe101, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc0005fe0f0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
        /home/travis/.gimme/versions/go/src/net/http/server.go:688 +0xd5

goroutine 36 [IO wait]:   
internal/poll.runtime_pollWait(0x7f053c4b8a00, 0x72, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000240198, 0x72, 0x0, 0x1, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000240080, 0xc0002c1bd1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000240080, 0xc0002c1bd1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000796000, 0xc0002c1bd1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc0002c1bc0)
        /home/travis/.gimme/versions/go/src/net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
        /home/travis/.gimme/versions/go/src/net/http/server.go:688 +0xd5

goroutine 13 [chan send]: 
text/template/parse.(*lexer).emit(...)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:157
text/template/parse.lexLeftDelim(0xc0006ec180, 0xa9c200)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:307 +0x1e5
text/template/parse.(*lexer).run(0xc0006ec180)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:223 +0x14b

goroutine 37 [runnable]:  
text/template/parse.(*lexer).emit(...)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:157
text/template/parse.lexText(0xc000240580, 0xa9c230)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:269 +0x4fd
text/template/parse.(*lexer).run(0xc000240580)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:223 +0x14b

goroutine 23 [runnable]:  
text/template/parse.(*lexer).emit(...)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:157
text/template/parse.lexText(0xc0005e2100, 0xa9c230)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:269 +0x4fd
text/template/parse.(*lexer).run(0xc0005e2100)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:223 +0x14b

goroutine 51 [runnable]:  
text/template/parse.(*lexer).emit(...)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:157
text/template/parse.lexText(0xc000563b80, 0xa9c230)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:269 +0x4fd
text/template/parse.(*lexer).run(0xc000563b80)
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
        /home/travis/.gimme/versions/go/src/text/template/parse/lex.go:223 +0x14b
```

**Comment by pramsey** [comment]
I think I see where the problem is, but I've never triggered a race myself, so I'll be fixing this a little blind.

**Comment by pramsey** [comment]
Try the CI builds and see if things are better.

**Comment by HaudelardUpFactor** [comment]
Sorry for my relative ignorance but what are the CI Builds exactly and how hould I try them please ?

**Comment by pramsey** [comment]
Sorry, the system automatically creates new binaries on each commit in the "continuous integration" (CI) system, and those are the binaries referenced [here](https://github.com/crunchydata/pg_tileserv#download). So if you pull one of those they will include the latest code changes.

**Comment by HaudelardUpFactor** [comment]
Oh ok I get it thanks.

I've updated the tileserver with the last binary 3 days ago and until now no more problems.

Thank you very much for your reactivity !

**Comment by pramsey** [comment]
Wonderful news, thanks for reporting back.
